name: Build theme for OpenWRT

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build theme for OpenWRT ${{ matrix.version }} using ${{ matrix.lunch }}
    runs-on: ubuntu-latest

    env:
      cache-key: ${{ matrix.version }}-${{ matrix.lunch }}-material3

    strategy:
      fail-fast: false
      matrix:
        lunch:
          - netgear_r6020
        version:
          - main
          - v24.10.2

    steps:
      - name: Restore cache of OpenWRT builder if it exists
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: openwrt-builder
          key: ${{ env.cache-key }}

      - name: Keep the OpenWRT source tree safe
        run: |
          if [ -d openwrt-builder/src ]; then
            mv openwrt-builder/src src
          fi

      - name: Clone the OpenWRT builder
        uses: actions/checkout@v4
        with:
          path: openwrt-builder
          repository: JoshuaDoes/openwrt-builder

      - name: Clone theme into themes feed
        uses: actions/checkout@v4
        with:
          path: openwrt-builder/feeds/themes/luci-theme-material3

      - name: Restore the OpenWRT source tree if it exists
        run: |
          if [ -d src ]; then
            mv src openwrt-builder/src
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext libncurses-dev libssl-dev python3-setuptools \
            rsync unzip zlib1g-dev file wget python3 python3-pip libelf-dev ccache \
            qemu-utils

      - name: Sync the source trees
        run: |
          set +e
          cd openwrt-builder
          cp -R .github/workflows/openwrt-build/* .
          . build/envsetup
          sync "${{ matrix.version }}"
          lunch "${{ matrix.lunch }}"
          sync
          cd ..

      - name: Build the Material3 theme
        run: |
          set +e
          cd openwrt-builder
          . build/envsetup
          lunch "${{ matrix.lunch }}"
          package luci-theme-material3
          pkg="$(ls $OUTPKG/themes/luci-theme-material3*)"
          name="$(basename $pkg)"
          {
            echo "pkg=$pkg"
            echo "name=$name"
          } >> $GITHUB_ENV
          cd ..

      - name: Upload the Material3 theme
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ${{ env.pkg }}
          compression-level: 0
          if-no-files-found: error

      - name: Clean the builder outputs
        run: |
          set +e
          cd openwrt-builder
          . build/envsetup
          clean
          cd ..

      - name: Delete previous OpenWRT builder cache before saving new
        if: ${{ steps.restore-cache.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete "${{ env.cache-key }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Save OpenWRT builder cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: openwrt-builder
          key: ${{ env.cache-key }}
